class RegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_user!, :only => :token

  def create
    super
    if @user.save
      @user.categories.create(name:"Mortgage or Rent")
      @user.categories.create(name:"Property Tax")
      @user.categories.create(name:"Utilities")
      @user.categories.create(name:"Property Maintenance/Condo Fees")
      @user.categories.create(name:"House Insurance")
      @user.categories.create(name:"Furniture & Home Decor")
      @user.categories.create(name:"Child/Spousal or other Family Support")
      @user.categories.create(name:"Child Care")
      @user.categories.create(name:"Kids' Allowances")
      @user.categories.create(name:"Kids' Clothing")
      @user.categories.create(name:"Kids' Toys")
      @user.categories.create(name:"Kids' Activities")
      @user.categories.create(name:"Car Payments")
      @user.categories.create(name:"Insurance Licence & Plate Fees")
      @user.categories.create(name:"Gas/Oil")
      @user.categories.create(name:"Repairs")
      @user.categories.create(name:"Public Transportation")
      @user.categories.create(name:"Tolls/Taxi/Parking/Traffic Tickets")
      @user.categories.create(name:"Automotive Store")
      @user.categories.create(name:"Life and Health Insurance")
      @user.categories.create(name:"Doctor Fees, Dentist, Optometrist, Prescription and Other Medical Costs")
      @user.categories.create(name:"Cable/Satellite")
      @user.categories.create(name:"Telephone and Cellphone")
      @user.categories.create(name:"Internet")
      @user.categories.create(name:"Groceries")
      @user.categories.create(name:"Personal Care")
      @user.categories.create(name:"Clothes, Jewellery Accessories")
      @user.categories.create(name:"Hair and Spa Services")
      @user.categories.create(name:"Education")
      @user.categories.create(name:"Entertainment")
      @user.categories.create(name:"Interests and Hobbies")
      @user.categories.create(name:"Club Dues")
      @user.categories.create(name:"Gambling")
      @user.categories.create(name:"Cigarettes")
      @user.categories.create(name:"Cycle and Outdoor/Sports Store")
      @user.categories.create(name:"Electronics")
      @user.categories.create(name:"Discount Store")
      @user.categories.create(name:"Drugstore")
      @user.categories.create(name:"Pet")
      @user.categories.create(name:"Gifts")
      @user.categories.create(name:"Vacation")
      @user.categories.create(name:"Charity")
      @user.categories.create(name:"Bank Fees")
      @user.categories.create(name:"Taxes Owed")
      @user.categories.create(name:"Debt Repayment")
    end
  end
end
